services:
  etcd:
    image: quay.io/coreos/etcd:v3.6.1
    command:
      - /usr/local/bin/etcd
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-client-urls=http://0.0.0.0:2379
    ports:
      - "2379:2379"

  kafka:
    image: bitnami/kafka:3.9
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"

  collector-a:
    build: .
    environment:
      COLLECTOR_ID: collector-a
      ETCD_ENDPOINTS: http://etcd:2379
      KAFKA_BROKERS: kafka:9092
      HTTP_ADDR: :8080
    ports:
      - "8080:8080"
    depends_on:
      - etcd
      - kafka

  collector-b:
    build: .
    environment:
      COLLECTOR_ID: collector-b
      ETCD_ENDPOINTS: http://etcd:2379
      KAFKA_BROKERS: kafka:9092
      HTTP_ADDR: :8080
    depends_on:
      - etcd
      - kafka
